version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: thursday
      time: "06:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    groups:
      react-runtime:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
    schedule:
      interval: weekly
      day: thursday
      time: "06:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
