packages:
  - "."
  - "example"
minimumReleaseAge: 0
trustPolicy: allow
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@commitlint/cli@21.2.0"
  - "@commitlint/config-conventional@21.2.0"
  - "@commitlint/config-validator@21.2.0"
  - "@commitlint/ensure@21.2.0"
  - "@commitlint/format@21.2.0"
  - "@commitlint/is-ignored@21.2.0"
  - "@commitlint/lint@21.2.0"
  - "@commitlint/load@21.2.0"
  - "@commitlint/message@21.2.0"
  - "@commitlint/parse@21.2.0"
  - "@commitlint/read@21.2.0"
  - "@commitlint/resolve-extends@21.2.0"
  - "@commitlint/rules@21.2.0"
  - "@commitlint/top-level@21.2.0"
  - "@commitlint/types@21.2.0"
  - vite@8.1.2
overrides:
  esbuild: ^0.28.1
